services:
  wingman-uploader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wingman-uploader
    environment:
      ACCOUNT_NAME: ${ACCOUNT_NAME}
      ARCDPS_LOG_DIR: /var/lib/gw2logs/arcdps.cbtlogs
      WINGMAN_UPLOADED_DIR: /var/lib/gw2logs/.wingmanUploaded
      IGNORE_OLD_LOGS: false
      RETRY_FAILED_UPLOADS: true
      RETRY_FREQUENCY: 60
      MAX_RETRIES: 5
    volumes:
      - "${ARCDPS_LOG_DIR}:/var/lib/gw2logs/arcdps.cbtlogs"
      - "${WINGMAN_UPLOADED_DIR}:/var/lib/gw2logs/.wingmanUploaded"
    restart: unless-stopped
